[package]
name = "hiero-did-client"
version.workspace = true
edition.workspace = true
repository.workspace = true
license.workspace = true
description = "Hedera client management for did:hedera SDK"
keywords = ["did", "hedera", "client", "sdk"]
categories = ["api-bindings"]

[dependencies]
hiero-did-core = { workspace = true }
hiero-sdk = { workspace = true }
serde = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }
rust_decimal = { workspace = true }

[dev-dependencies]
dotenvy = { workspace = true }
