[package]
name = "hiero-did-method"
version.workspace = true
edition.workspace = true
repository.workspace = true
license.workspace = true
description = "Parser and validators for did:hedera identifiers"
keywords = ["did", "hedera", "parser", "validator"]
categories = ["parser-implementations", "cryptography"]

[dependencies]
hiero-did-core = { workspace = true }
bs58 = { workspace = true }
thiserror = { workspace = true }
